/*
 * Auto-generated by generate_assets.py — do not edit.
 * Embeds the Anthropic claude-desktop-buddy bufo GIFs (96x100) so they can
 * be displayed via lv_gif without a filesystem dependency.
 * Source: https://github.com/anthropics/claude-desktop-buddy/tree/main/characters/bufo
 * License: MIT (matches the upstream repo).
 */
#pragma once

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

LV_ATTRIBUTE_EXTERN_DATA extern const lv_image_dsc_t bufo_idle;
LV_ATTRIBUTE_EXTERN_DATA extern const lv_image_dsc_t bufo_sleep;
LV_ATTRIBUTE_EXTERN_DATA extern const lv_image_dsc_t bufo_busy;
LV_ATTRIBUTE_EXTERN_DATA extern const lv_image_dsc_t bufo_attention;
LV_ATTRIBUTE_EXTERN_DATA extern const lv_image_dsc_t bufo_celebrate;
LV_ATTRIBUTE_EXTERN_DATA extern const lv_image_dsc_t bufo_dizzy;
LV_ATTRIBUTE_EXTERN_DATA extern const lv_image_dsc_t bufo_heart;

#ifdef __cplusplus
}
#endif
