#!/usr/bin/env python3
"""
Convert each bufo*.gif into a C source file consumable by LVGL's lv_gif.

LVGL's lv_gif_set_src accepts a pointer to a lv_image_dsc_t whose .data
points to the raw GIF bytes and .data_size is the byte count. The header
type is LV_IMG_HEADER_FILE (0x10) so LVGL knows to forward the bytes to
the GIF decoder rather than interpret them as raw pixels.

Output: one .c file per GIF, exposing
    const lv_image_dsc_t bufo_<state>;
and a matching header bufo_images.h listing every descriptor.

Run from the assets/claude_bufo directory:
    python3 generate_assets.py
"""
import os
import sys

THIS_DIR = os.path.dirname(os.path.abspath(__file__))

# (filename, C identifier suffix) — one entry per GIF we ship.
# Idle rotation and dizzy/heart are intentionally limited to keep flash
# usage reasonable; Phase 4 can be enriched later.
GIF_STATES = [
    ("idle_0.gif", "idle"),
    ("sleep.gif", "sleep"),
    ("busy.gif", "busy"),
    ("attention.gif", "attention"),
    ("celebrate.gif", "celebrate"),
    ("dizzy.gif", "dizzy"),
    ("heart.gif", "heart"),
]

HEADER = """\
/*
 * Auto-generated by generate_assets.py — do not edit.
 * Embeds the Anthropic claude-desktop-buddy bufo GIFs (96x100) so they can
 * be displayed via lv_gif without a filesystem dependency.
 * Source: https://github.com/anthropics/claude-desktop-buddy/tree/main/characters/bufo
 * License: MIT (matches the upstream repo).
 */
"""

HEADER_H = """\
#pragma once

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

"""

FOOTER_H = """
#ifdef __cplusplus
}
#endif
"""


def emit_c(gif_path: str, c_symbol: str) -> str:
    with open(gif_path, "rb") as f:
        data = f.read()

    # Emit a byte array + a lv_image_dsc_t descriptor compatible with LVGL 9.
    # lv_gif ignores most header fields (it parses the GIF bytes directly),
    # but the magic field MUST be LV_IMAGE_HEADER_MAGIC so LVGL routes the
    # pointer through the right decoder. cf is unused for GIF, w/h are for
    # layout pre-allocation; stride/reserved can stay 0 (decoder fills them).
    lines = []
    lines.append(f"static const uint8_t bufo_{c_symbol}_data[{len(data)}] = {{")
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        lines.append("    " + "".join(f"0x{b:02x}, " for b in chunk).rstrip())
    lines.append("};")
    lines.append("")
    lines.append("const lv_image_dsc_t bufo_" + c_symbol + " = {")
    lines.append("    .header = {")
    lines.append("        .magic = LV_IMAGE_HEADER_MAGIC,")
    lines.append("        .cf = LV_COLOR_FORMAT_ARGB8888,  /* ignored by lv_gif decoder */")
    lines.append("        .flags = 0,")
    lines.append("        .w = 96,")
    lines.append("        .h = 100,")
    lines.append("        .stride = 0,  /* filled by the GIF decoder */")
    lines.append("        .reserved_2 = 0,")
    lines.append("    },")
    lines.append(f"    .data_size = {len(data)},")
    lines.append(f"    .data = bufo_{c_symbol}_data,")
    lines.append("    .reserved = NULL,")
    lines.append("    .reserved_2 = NULL,")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    decls = []
    for filename, symbol in GIF_STATES:
        gif_path = os.path.join(THIS_DIR, filename)
        if not os.path.exists(gif_path):
            print(f"warning: missing {filename}, skipping", file=sys.stderr)
            continue
        c_path = os.path.join(THIS_DIR, f"bufo_{symbol}.c")
        with open(c_path, "w") as f:
            f.write(HEADER)
            f.write("\n")
            # Include the central header so the lv_image_dsc_t struct + the
            # extern declaration of our own symbol are both visible. Avoids
            # generating one header per gif (only bufo_images.h is needed).
            f.write('#include "bufo_images.h"\n\n')
            f.write(emit_c(gif_path, symbol))
        size = os.path.getsize(gif_path)
        print(f"  bufo_{symbol}.c <- {filename} ({size} bytes)")
        decls.append(f"LV_ATTRIBUTE_EXTERN_DATA extern const lv_image_dsc_t bufo_{symbol};")

    header_path = os.path.join(THIS_DIR, "bufo_images.h")
    with open(header_path, "w") as f:
        f.write(HEADER)
        f.write(HEADER_H)
        f.write("\n".join(decls))
        f.write("\n")
        f.write(FOOTER_H)
    print(f"  bufo_images.h ({len(decls)} descriptors)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
